In [1]:
# The code is for perceptron learning algorithm with backpropagation for multi-layer neural network
import numpy as np

In [2]:
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size, learning_rate=0.1):
        self.input_size = input_size
        # The size of the hidden layer
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.learning_rate = learning_rate
        
        # Initialize weights and biases
        self.weights_input_hidden = np.random.randn(self.input_size, self.hidden_size)
        self.bias_hidden = np.zeros((1, self.hidden_size))
        self.weights_hidden_output = np.random.randn(self.hidden_size, self.output_size)
        self.bias_output = np.zeros((1, self.output_size))

        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_derivative(self, x):
        return x * (1 - x)
    
    def forward(self, X):
        # Forward pass
        self.hidden_activation = self.sigmoid(np.dot(X, self.weights_input_hidden) + self.bias_hidden)
        self.output = self.sigmoid(np.dot(self.hidden_activation, self.weights_hidden_output) + self.bias_output)
        return self.output
    
    def backward(self, X, y, output):
        # Backpropagation
        error = y - output
        d_output = error * self.sigmoid_derivative(output)
        
        error_hidden = d_output.dot(self.weights_hidden_output.T)
        d_hidden = error_hidden * self.sigmoid_derivative(self.hidden_activation)
        
        # Update weights and biases
        self.weights_hidden_output += self.hidden_activation.T.dot(d_output) * self.learning_rate
        self.bias_output += np.sum(d_output, axis=0, keepdims=True) * self.learning_rate
        self.weights_input_hidden += X.T.dot(d_hidden) * self.learning_rate
        self.bias_hidden += np.sum(d_hidden, axis=0, keepdims=True) * self.learning_rate
    
    def train(self, X, y, epochs):
        for epoch in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output)
            if epoch % 100 == 0:
                loss = np.mean(np.square(y - output))
                print(f'Epoch {epoch}, Loss: {loss}')
    
    def predict(self, X):
        output = self.forward(X)
        # Apply threshold to output to get the predicted class labels
        thresholded_output = np.where(output >= 0.5, 1, 0)
        return thresholded_output
    
    def evaluate(self, X, y):
        output = self.forward(X)
        loss = np.mean(np.square(y - output))
        return loss
    
    def accuracy(self, y_true, y_pred):
        return np.sum(y_true == y_pred) / len(y_true)

In [3]:
input_size = 2
hidden_size = 3
output_size = 1

# Create the neural network
nn = NeuralNetwork(input_size, hidden_size, output_size)

# Dummy training data (XOR problem)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [4]:
# Train the neural network
nn.train(X, y, epochs=1000)

# Predict
print("Predictions:")
print(nn.predict(X))

Epoch 0, Loss: 0.28017396185177135
Epoch 100, Loss: 0.24720750159465316
Epoch 200, Loss: 0.24571115323755977
Epoch 300, Loss: 0.2440231172272189
Epoch 400, Loss: 0.24196907447928
Epoch 500, Loss: 0.23939992223061107
Epoch 600, Loss: 0.23618587557767148
Epoch 700, Loss: 0.23221841618687758
Epoch 800, Loss: 0.22741890916303514
Epoch 900, Loss: 0.22175893586638828
Predictions:
[[0]
 [0]
 [1]
 [1]]


In [5]:
# Getting the weights
print("Weights:")
print(nn.weights_input_hidden)

# Getting the biases
print("Biases:")
print(nn.bias_hidden)

# Evaluate the model
print("Loss:")
print(nn.evaluate(X, y))


Weights:
[[-0.86157749  1.9148433   0.8379638 ]
 [ 3.02726844  2.04694547 -1.97923444]]
Biases:
[[ 0.38823942 -0.03955204 -0.68910992]]
Loss:
0.21529458225324008
